### ISSUE TITLE
unable to leave comments for Giscus on your site

### ISSUE THREAD

**Issue by kwchang0831** [kwaa/blog#1]
According to your comment on [https://kwaa.moe/@kwa](https://kwaa.moe/@kwa)
> 藍+85CD @kwa@kwaa.moe
> 🤔 我博客的评论门槛是不是太高了？从换 Urara 到现在没收到一条评论
> 还是说放太多选项会导致选择困难，或许该把 Disqus 删掉

I tried to leave you a comment on the [https://kwaa.dev/intro-urara/re](https://kwaa.dev/intro-urara/re).

Got the following error in the console:
```
widget-ab0d97175bfd6f88.js:1          
GET https://giscus.kwaa.dev/api/discussions?repo=kwaa%2Fcomments&term=intro-urara%2Fre&number=0&first=15 404
```

It seems like you don't have your discussion board enabled for this git repo neither.

You might want to double check it.

By the way, thanks for your awesome blog starter.
Outstanding work. I really love it.

**Comment by kwaa** [comment]
> According to your comment on https://kwaa.moe/@kwa
> 
> > 藍+85CD @[kwa@kwaa.moe](mailto:kwa@kwaa.moe)
> > 🤔 我博客的评论门槛是不是太高了？从换 Urara 到现在没收到一条评论
> > 还是说放太多选项会导致选择困难，或许该把 Disqus 删掉
> 
> I tried to leave you a comment on the https://kwaa.dev/intro-urara/re.
> 
> Got the following error in the console:
> 
> ```
> widget-ab0d97175bfd6f88.js:1          
> GET https://giscus.kwaa.dev/api/discussions?repo=kwaa%2Fcomments&term=intro-urara%2Fre&number=0&first=15 404
> ```
> 
> It seems like you don't have your discussion board enabled for this git repo neither.
> 
> You might want to double check it.

Hmmm... I really don't maintain [urara_giscus](https://github.com/kwaa/urara_giscus) much. (will look at it in the next few days)
Maybe you can try sending Webmention via [commentparade](https://commentpara.de)
 
> By the way, thanks for your awesome blog starter. Outstanding work. I really love it.

Thanks for the favorite. In that case, how about keeping a "Powered by Urara" link?

as a blog with sufficient content I can write into README.md and form a good loop.

**Comment by kwchang0831** [comment]
All done on my part. ❤️
